In [9]:
import numpy as np
from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle
from sklearn.metrics import roc_curve, auc
import numpy as np
import cv2
import keras
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout,  BatchNormalization , Activation
from keras.preprocessing.image import ImageDataGenerator
import tensorflow as tf
from keras.models import load_model
from sklearn.preprocessing import label_binarize
from sklearn import metrics

In [2]:
model = tf.keras.models.load_model('corona-ensemble-final.h5')

In [26]:
test_x = np.load('testx.npy')

In [41]:
test_y = np.load('testy.npy')

In [31]:
results = model.evaluate(test_x, test_y)

604/604 [==============================] - 87s 145ms/sample - loss: 0.0604 - accuracy: 0.9801


In [42]:
test_y = keras.utils.to_categorical(test_y, 3)

In [43]:
y_int = np.argmax(test_y, axis=1)

In [37]:
yhat = model.predict(test_x, verbose=0)

In [38]:
ypred_int = np.argmax(yhat, axis=1)

In [44]:
print(metrics.confusion_matrix(y_int, ypred_int))

[[277   0   3]
 [  0 160   2]
 [  1   6 155]]


In [45]:
print(metrics.classification_report(y_int, ypred_int, digits=3))

              precision    recall  f1-score   support

           0      0.996     0.989     0.993       280
           1      0.964     0.988     0.976       162
           2      0.969     0.957     0.963       162

    accuracy                          0.980       604
   macro avg      0.976     0.978     0.977       604
weighted avg      0.980     0.980     0.980       604

